---
framework: mocha
tier: small
blocklist:
  - "test/options.spec.ts##options##cwd##"
  - "./test/options.spec.ts##options##output##should work"
  - "./test/target.spec.ts##Targets##should stringify and toString"
postMerge:
  pattern: 
    - "./test/**/*.spec.ts"
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm ci
postRun:
     command:
        - node --version
version: 2.4.1
containerImage: lambda2dockerhub/synapse:demo
